version: "2"
volumes: 
  sitewise-data:
  greengrass-logs:
services:
  opc:
    build: ./opc
    restart: always
    ports: 
      - "26543:26543"
  greengrass:
    build: ./greengrass
    restart: always
    privileged: true
    volumes:
      - "sitewise-data:/var/sitewise"
      - "greengrass-logs:/greengrass/ggc/var/log"
    depends_on:
      - opc
    ports: 
      - "8883:8883"
  logstash:
    build: ./logstash
    restart: always
    ports:
      - "5044:5044"
